Review
robotkoruslan/Notes_app pull request #1
Opened 2021-03-21 09:53 UTC by robotkoruslan

2021-03-22 10:21 UTC, Vitaliy-Svinchyak requested changes

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/controller/auth.dart
> +    print(error);
Какой-нибудь месседж в скаффолде можно показывать

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/controller/auth.dart
> +        'provider': 'facebook',
Провайдер должен быть енамом

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/add_note.dart
> +                            title = _val;
this

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/add_note.dart
> +                  Form(
Тут форма не нужна, ты ее не используешь

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/add_note.dart
> +                              description = _val;
this

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/home_page.dart
> +            if (snapshot.hasData) {
```
if (!snapshot.hasData) {
             return const Center(
                child: CircularProgressIndicator(),
              );
}
// everything else
```

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/view_note.dart
> +              padding: const EdgeInsets.all(15),
В таком случае можно просто Padding виджет заюзать

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/view_note.dart
> +                        height: MediaQuery.of(context).size.height * 0.75,
Это ок, но попробуй запустить приложуху на маленьких смартфонах. В других местах может поехать верстка

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/widgets/sign_in_button.dart
> +          await handler(context);
this

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/widgets/sign_in_button.dart
> +  final Function handler;
лучше использовать тип `VoidCallback`

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/widgets/sign_in_button.dart
> +  final Function handler;
И хендлер так себе название свойства, хендлер для чего? Лучше ее также назвать `onPressed`

2021-03-22 10:21 UTC, Vitaliy-Svinchyak commented on lib/screens/home_page.dart
> +                        DateFormat.yMMMd().format(_dateTime).toString();
Для форматирование надо выделить отдельный сервис

2021-03-22 11:26 UTC, Dsazz requested changes

2021-03-22 11:26 UTC, Dsazz commented on lib/controller/auth.dart
> +        if (doc.exists) {
Я бы все-таки обернул эту логику работы с базой  и авторизацией в какие-то сервисы. У меня обычно это `AuthenticationRepository` и `UserRepository`

2021-03-22 11:26 UTC, Dsazz commented on lib/controller/auth.dart
> +          Navigator.of(context).pushReplacement(
Ты дублируешь этот код в четырех местах. Как минимум можно вынести этот функционал за if/else 
```
          Navigator.of(context).pushReplacement(
            MaterialPageRoute(
              builder: (builder) => HomePage(),
            ),
          );
          ```

2021-03-22 11:26 UTC, Dsazz commented on lib/controller/auth.dart
> +          doc.reference.update(userData);
тоже самое

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/add_note.dart
> +    final CollectionReference ref = FirebaseFirestore.instance
обернуть в репозиторий. лучше избавлять UI от бизнес логики

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/home_page.dart
> +                  value == '1' ? _signOut() : print(_currentUser);
не юзай магию ) оборачивай в ENUM или константы

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/home_page.dart
> +  CollectionReference ref = FirebaseFirestore.instance
Обернуть в репозитарий  и две строки выше тоже

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/home_page.dart
> +                    value: '1',
магия

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/home_page.dart
> +    await FirebaseAuth.instance.signOut();
обернуть

2021-03-22 11:26 UTC, Dsazz commented on lib/screens/view_note.dart
> +    await widget.ref.delete();
Х___х оберни тоже. Не разрешай UI делать такие операции напрямую

2021-03-26 20:50 UTC, robotkoruslan commented on lib/screens/add_note.dart
> +                        height: MediaQuery.of(context).size.height * 0.75,
Это я уже убрал.

2021-03-27 09:14 UTC, Dsazz requested changes

2021-03-27 09:14 UTC, Dsazz commented on lib/services/authentication_repository.dart
> +Future google() async {
Начнем с названия.. 
Назовем метод "Тумбочка". Такое название вряд ли описывает какое-то действие. А метод в репозитории - это зачастую глагол.

2021-03-27 09:14 UTC, Dsazz commented on lib/services/authentication_repository.dart
> +  } else {
тут можно упростить код, убери else

2021-03-27 09:14 UTC, Dsazz commented on lib/services/authentication_repository.dart
> +Future facebook() async {
Тоже самое

2021-03-27 09:14 UTC, Dsazz commented on lib/services/authentication_repository.dart
> +
Оберни все в класс

2021-03-27 09:14 UTC, Dsazz commented on lib/services/authentication_repository.dart
> +  await Navigator.of(context).pushReplacement(
методы атомарные, помним об этом

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +Future signInGoogle({BuildContext context, Function kindOfAuth}) async {
signInGoogle явно не ответственность UserRepository. Я немного поломал голову, чтобы зачем тут kindOfAuth. А потом понял, что ты сам наткнулся на грабли "ответственности" класса. Вот тебе явный пример усложнения кода, когда класс выполняет то, что по описанию не должен был. 

Ответственность UserRepository отдать/обновить/удалить данные о пользователе. Все!
Ответственность AuthentificationRepository заниматься авторизацией. 

В твоем случае AuthentificationRepository должен был получить данные о пользователе
А UserRepository должен был принять эти данные и ничего не знать о AuthentificationRepository и его методах

И оберни все в классы )

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +      'provider': 'google',
константа должна тут быть

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +    await Navigator.of(context).pushReplacement(
это выносим на уровень вверх
Соблюдаем единую ответственность для каждого метода

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +    ScaffoldMessenger.of(context).showSnackBar(
единая ответственность. выносим отсюда

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +      .doc(FirebaseAuth.instance.currentUser.uid)
забавно ты ввел метод выше и не используешь его

2021-03-27 09:14 UTC, Dsazz commented on lib/services/user_repository.dart
> +  final currentUser = FirebaseAuth.instance.currentUser;
можно просто return сделать без переменной

2021-03-27 09:14 UTC, Dsazz commented on lib/screens/sign_in.dart
> +                              context: this.context, kindOfAuth: facebook),
тебя не смущает название метода и то, что ты передаешь ?)) у тебя должно быть явно два отдельных метода для SignIn.
Удали kindOfAuth этот и лучше так не делай. Тут явно идет усложнение того, что можно намного проще сделать. Я ниже описал все подробнее

2021-04-03 14:10 UTC, Dsazz requested changes

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/create_note_view_model.dart
> +    final CollectionReference ref = _userService.currentRef();
не, это все дичь. сделай `currentRef` private. 
всю эту логику ниже оберни в новый метод UserService(который должен быть UserRepository)

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/login_view_model.dart
> +    if (result is bool) {
в смысле ? тебе типа пофиг, что вернется в результате ? тут должна быть проверка на true, а проще просто написать if(result)

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/login_view_model.dart
> +    await _navigationService.navigateTo(LoginViewRoute);
а если exception будет ?

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/startup_view_model.dart
> +  Future handleStartUpLogic() async {
у тебя выше такой же редирект, получается дублирование
что-то не так с архитектурой

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/view_note_model.dart
> +    await ref.delete();
не, так нельзя. это ответственность Repository

2021-04-03 14:10 UTC, Dsazz commented on lib/viewmodels/home_view_model.dart
> +      _userService.currentRef().get();
не юзай currentRef вне Repository, оберни это все дело в UserRepository

2021-04-04 12:50 UTC, Dsazz requested changes

2021-04-04 12:50 UTC, Dsazz commented on lib/locator.dart
> +    ..registerLazySingleton(() => NavigationService())
добавь типы 
```
    ..registerLazySingleton<NavigationService>(() => NavigationService())

2021-04-04 12:50 UTC, Dsazz commented on lib/models/notes.dart
> +  Map<String, dynamic> fromData() => {
не, тут название должно быть toJson
ты ведь не создаешь новый экземпляр Notes
кстати название модели не должно быть в множественном числе

2021-04-04 12:50 UTC, Dsazz commented on lib/repository/user_repository.dart
> +  Future createUserinFirebase(UserData userData) async {
просто `create` будет достаточно
в итоге будет читаться так `userRepository.create(userData)`
Репозиторий и так декларирует работу с базой данных, по-этому не нужно это писать в названии метода

2021-04-04 12:50 UTC, Dsazz commented on lib/repository/user_repository.dart
> +  Future deleteNoteFromDB(DocumentReference ref) async {
дичь какая-то
ты тут можешь абсолютно любой экземпляр DocumentReference передать
что-то не так с архитектурой

2021-04-04 12:50 UTC, Dsazz commented on lib/repository/user_repository.dart
> +  CollectionReference currentRef() {
Давай разберем название `currentRef` в репозитории UserRepository
Я например ожидаю получить текущую запись о пользовате в БД, а не коллекцию notes

2021-04-04 12:50 UTC, Dsazz commented on lib/repository/user_repository.dart
> +  Future<QuerySnapshot> getAllNotesFromDB() async => currentRef().get();
выглядит будто тут должен быть другой репозиторий 
минимум нужно поменять название getAllUserNotes
(не нужно тебе это fromDB и тд)

2021-04-04 12:50 UTC, Dsazz commented on lib/ui/views/login_view.dart
> +                              ImagePath.imgLogin,
мне кажется избыточным префикс `img*`
ты ведь и так вызов делаешь из Image! Path

2021-04-04 12:50 UTC, Dsazz commented on lib/viewmodels/create_note_view_model.dart
> +  void add({String title, String description}) {
хз, спорное решение конечно юзать ViewModel и делегировать ей вызов Repository.

p.s. это просто мои размышления в слух

2021-04-04 12:50 UTC, Dsazz commented on lib/viewmodels/create_note_view_model.dart
> +    _userRepository.addNoteInDB(data);
странная ответственность
ты вызываешь addNote и добавляешь его в отдельную коллекцию Notes в базе из сервиса UserRepository, который должен отвечать за user

2021-04-04 12:50 UTC, Dsazz commented on lib/viewmodels/home_view_model.dart
> +  User currentUserFromDB() => _userRepository.getCurrentUserFromDB();
убери суффиксы fromDB это не имеет смысла

2021-04-04 12:50 UTC, Dsazz commented on lib/viewmodels/login_view_model.dart
> +      Exception('Some problem with auth');
тебя надо что-то решить со всеми обработками ошибок

на данный момент ты ловишь абсолютно все ошибок и прокидываешь наверх одну ни о чем не говорящую.

в итоге ты аннулируешь саму их ценность 

предлагаю пройтись по проекту и явно ловить каждую возможную ошибку
таким образом ты лучше поймешь все процессы, которые происходят в ходе выполнения программы

2021-04-04 16:56 UTC, Dsazz requested changes

2021-04-04 16:56 UTC, Dsazz commented on lib/repository/user_repository.dart
> +  User getCurrentUserFirebase() => FirebaseAuth.instance.currentUser;
Заметил, что тебе приходится тут приставку Firebase оставить ? 

Это из-за того, что брать данные из FirebaseAuth это не являеться ответственностью UserRepository. 
   Когда ты объявляешь репозиторий, то ты явно декларируешь "тут будут описаны операции взаимодействия с таблицей User и ничего больше". Благодаря этому у тебя выходят простые и понятные названия методов (create, delete, getAll и тд). 
   
   А вот когда тебе приходится сложно прилепить метод в контекст Класса, то это явный "запах"  ~~говнокода~~ того, что тебе нужно искать другое место для него (создать новый класс, или перенести в существующий)
   
   Вот так и выходит с FirebaseAuth.instance.currentUser
   Это явно ответственность какого-то AuthenticationRepository/AuthenticationHandler->getCurrentAuthUser

2021-04-07 10:40 UTC, Vitaliy-Svinchyak requested changes
Я так понимаю, тебе нужен сервис для диалогов и пустая прослойка только для того, чтобы иметь контекст и показывать модалки из моделей/сервисов?
Проще ловить ошибки на уровне виджетов, которые эти сервисы юзают. Так больше ошибок ловится одним кетчем и всегда есть контекст. И не запутаешься в неявных модалках

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/services/dialog_service.dart
> +class DialogService {
В чем смысл существования этого менеджера если он ничего не делает без помощи 1 единственного колбека? Лучше их уже совместить

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/managers/dialog_manager.dart
> +        builder: (context) => AlertDialog(
Можно сам диалог вынести в виджет и тогда этая пустая прослойка не нужна будет

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/managers/dialog_manager.dart
> +    final isConfirmationDialog = request.cancelTitle != null;
Эта логика должна быть внутри DialogRequest

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/models/dialog_models.dart
> +  final String fieldTwo;
Неизвестные филды какие-то. Даже не используются. Можно удалить и сам респонс будет иметь тип bool

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/models/user.dart
> +  final String provider;
Провайдер енамом должен быть

2021-04-07 10:40 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/busy_button.dart
> +              child: !widget.busy
Лучше идти не от отрицания. `widget.busy ? aa : bb`

2021-04-07 11:31 UTC, Vitaliy-Svinchyak requested changes

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/services/navigation_service.dart
> +  Future<dynamic> navigateTo(String routeName, {String arguments}) =>
Этот класс можно удалить и юзать `Navigator.of(context).pushNamed`

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/user_info_menu.dart
> +  const UserInfoMenu({Key key, this.logout, this.user}) : super(key: key);
@required

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/user_info_menu.dart
> +  final Function logout;
VoidCallback

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/user_info_menu.dart
> +  final Function logout;
& logoutCallback?

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/user_info_menu.dart
> +              value: "profileInfoButtonMenu",
enum

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/busy_button.dart
> +  final bool enabled;
not used?

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/ui/widgets/busy_button.dart
> +        onTap: () => widget.onPressed(),
По сути кнопка сама может знать когда она `busy`. С того момента как произошел тап и до тех пор, пока промис не зарезолвился. Ты можеть указать конкретный тип колбека и делать что-то типа:
 ```
 this.busy = true;
 await widget.onPressed();
 this.busy = false;
 ```
 Тогда весь менеджмент состояния остается спрятан внутри кнопки и не нужны дополнительные флаги в каждой "модели".

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/viewmodels/create_note_view_model.dart
> +class CreateNoteViewModel extends BaseModel {
По сути это не модели. Они не хранят никакие данные, а только делают запросы

2021-04-07 11:31 UTC, Vitaliy-Svinchyak commented on lib/viewmodels/create_note_view_model.dart
> +  Future addNote({String title, String description}) async {
Этот сервис можно удалить а сам метод перенести в виджет, который сейчас его использует

2021-04-07 11:36 UTC, Dsazz commented on lib/viewmodels/create_note_view_model.dart
> +  Future addNote({String title, String description}) async {
мне вообще эти ViewModel кажутся избыточными

2021-04-07 16:01 UTC, robotkoruslan commented on lib/main.dart
>          title: 'Notes App',
Не могу понять как это реализовать, как только я делаю иначе я то контекст теряю или стек. Я делал по аналогии https://medium.com/flutter-community/manager-your-flutter-dialogs-with-a-dialog-manager-1e862529523a

2021-04-09 07:45 UTC, merged